[package]
name = "sentiric-sip-uac"
version = "1.3.0" # Mimari değişim nedeniyle versiyon yükseltildi
edition = "2021"
description = "CLI Shell for Sentiric SIP UAC - Powered by uac-core."
authors = ["Sentiric Team"]
license = "AGPL-3.0"

[dependencies]
# --- THE NEW BRAIN ---
sentiric-sip-uac-core = { git = "https://github.com/sentiric/sentiric-sip-uac-core.git", branch = "main" }

# --- Utilities for CLI ---
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
chrono = "0.4"