[package]
name = "sentiric-sip-uac"
version = "1.0.0"
edition = "2021"
description = "Sentiric SIP User Agent Client."
authors = ["Sentiric Team"]
license = "AGPL-3.0"

[dependencies]
# UAC de aynı kararlı çekirdeği kullanmalı.

sentiric-sip-core = { git = "https://github.com/sentiric/sentiric-sip-core.git", tag = "v1.2.12" }
sentiric-rtp-core = { git = "https://github.com/sentiric/sentiric-rtp-core.git", tag = "v1.2.0" }